# Generated by Django 3.1.2 on 2020-10-08 00:43

from django.conf import settings
from django.db import migrations, models
import ssp.artifacts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=ssp.artifacts.models.artifact_file_name)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_hash', models.SlugField(blank=True, max_length=64, null=True)),
                ('mime_type', models.CharField(default='unkown', max_length=100)),
                ('file_encoding', models.CharField(default='unkown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('artifact_type', models.CharField(choices=[('F', 'File')], default='F', max_length=5)),
                ('artifact_pk', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=models.SET(ssp.artifacts.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
