# Generated by Django 3.1.2 on 2020-10-09 21:42

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import ssp.artifacts.models


class Migration(migrations.Migration):

    replaces = [('artifacts', '0001_initial'), ('artifacts', '0002_auto_20201009_0127'), ('artifacts', '0003_auto_20201009_1702'), ('artifacts', '0004_fileartifact_file_extension'), ('artifacts', '0005_auto_20201009_2104')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=ssp.artifacts.models.artifact_file_name)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_hash', models.SlugField(blank=True, max_length=64, null=True)),
                ('mime_type', models.CharField(default='unkown', max_length=100)),
                ('file_encoding', models.CharField(default='unkown', max_length=100)),
                ('file_extension', models.CharField(default='unknown', max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(default=1, on_delete=models.SET(ssp.artifacts.models.get_sentinel_user), to='users.user')),
                ('name', models.CharField(default='test', max_length=255)),
            ],
        ),
    ]
