# Generated by Django 3.1.2 on 2020-10-10 19:44

from django.conf import settings
from django.db import migrations, models
import ssp.utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artifacts', '0001_squashed_0005_auto_20201009_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileartifact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fileartifact',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET(ssp.utils.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileartifact',
            name='file_encoding',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileartifact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
