# Generated by Django 3.1.2 on 2020-10-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifact_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(blank=True, choices=[('F', 'File')], max_length=5, null=True),
        ),
    ]
