# Generated by Django 3.1.2 on 2020-10-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_auto_20201009_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('F', 'File')], default='F', max_length=5),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
