# Generated by Django 3.1.2 on 2020-10-09 21:04

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import ssp.artifacts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artifacts', '0004_fileartifact_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileartifact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileartifact',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=models.SET(ssp.artifacts.models.get_sentinel_user), to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileartifact',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Artifact',
        ),
    ]
