# Generated by Django 3.1.1 on 2020-09-18 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ssp.plans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('descrption', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=models.SET(ssp.plans.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvers', models.ManyToManyField(related_name='entry_approvals', to=settings.AUTH_USER_MODEL)),
                ('collaborators', models.ManyToManyField(related_name='entry_collaborations', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.control')),
                ('observers', models.ManyToManyField(related_name='entry_observations', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('PA', 'Pending Approval'), ('P', 'Published')], default='D', max_length=3)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('last_status', models.CharField(choices=[('D', 'Draft'), ('PA', 'Pending Approval'), ('P', 'Published')], default='D', max_length=3)),
                ('last_text', models.TextField(blank=True, null=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
                ('approvals', models.ManyToManyField(through='plans.Approval', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.entry')),
            ],
            options={
                'ordering': ['-modified_on'],
                'get_latest_by': 'modified_on',
            },
        ),
        migrations.AddField(
            model_name='approval',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.detail'),
        ),
        migrations.AddField(
            model_name='approval',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(ssp.plans.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('user', 'detail')},
        ),
    ]
