# Generated by Django 3.1.1 on 2020-09-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        ('plans', '0002_auto_20200918_2312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('plan', 'control')},
        ),
    ]
