# Generated by Django 3.1.2 on 2020-10-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_auto_20200920_0221"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approval", options={"ordering": ["created_on"]},
        ),
        migrations.AddField(
            model_name="approval",
            name="plan",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="plans.plan"
            ),
            preserve_default=False,
        ),
    ]
