# Generated by Django 3.1.2 on 2020-10-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0001_initial"),
        ("plans", "0004_auto_20201006_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="plan",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="plans.plan"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="root_control",
            field=models.ForeignKey(
                default=20,
                on_delete=django.db.models.deletion.CASCADE,
                to="controls.control",
            ),
            preserve_default=False,
        ),
    ]
