# Generated by Django 3.1.2 on 2020-10-14 23:52

from django.conf import settings
from django.db import migrations, models
import ssp.plans.models
import ssp.utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0005_auto_20201012_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to=ssp.plans.models.artifact_file_name)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_hash', models.SlugField(blank=True, max_length=64, null=True)),
                ('mime_type', models.CharField(default='unkown', max_length=100)),
                ('file_extension', models.CharField(default='unknown', max_length=25)),
                ('file_encoding', models.CharField(default='unknown', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=models.SET(ssp.utils.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
