# Generated by Django 3.1.2 on 2020-10-14 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_fileartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileartifact',
            name='plan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
            preserve_default=False,
        ),
    ]
