# Generated by Django 3.1.2 on 2020-10-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_fileartifact_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='file_artifacts',
            field=models.ManyToManyField(to='plans.FileArtifact'),
        ),
    ]
